name: First
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

  job:
    init:
      run_on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x ]

      steps: 
        - uses: actions/checkout@v4
        - name: Staging Node ${{ matrix.node-version }}

        - name: install modules
          run: npm run
        
        - name: build project
          run: npm run build

        - name: unit test 
          run: npm run test:unit
        
        - name: e2e test
          run: npm run test:e2e
        
        - name: lint code
          run: npm run lint

        